[package]
name = "zjstatus"
version = "0.18.0-rc1"
authors = ["Daniel Jankowski"]
edition = "2018"

[[bin]]
name = "zjstatus"
bench = false

[lib]
bench = false

[features]
bench = []
tracing = []

[dependencies]
zellij-tile = "0.40.1"
chrono = { version = "0.4.38", default-features = false, features = ["unstable-locales"] }
regex = "1.10.5"
chrono-tz = "0.9.0"
anyhow = "1.0.86"
anstyle = "1.0.7"
uuid = { version = "1.10.0", features = ["v4"] }
lazy_static = "1.5.0"
cached = { version = "0.52.0", features = ["wasm"] }
console = "0.15.8"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
kdl = "4.6.0"
rstest = "0.21.0"
itertools = "0.13.0"

[dev-dependencies]
criterion = { version = "0.5.1", default-features = false, features = [
    "html_reports",
] }

[[bench]]
name = "benches"
harness = false

[[bench]]
name = "widgets"
harness = false
